services:
  - type: web
    name: kinalapp
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8302
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: kinalapp-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: kinalapp-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: kinalapp-db
          property: password
    healthCheckPath: /login

  - type: redis
    name: kinalapp-redis
    ipAllowList: []

databases:
  - name: kinalapp-db
    databaseName: kinalapp
    user: kinalapp
