services:
  - type: web
    name: kinalapp
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8302
    healthCheckPath: /login

databases:
  - name: kinalapp-db
    databaseName: kinalapp
    user: kinalapp
